// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GreeterService is an autogenerated mock type for the GreeterService type
type GreeterService struct {
	mock.Mock
}

// Greet provides a mock function with given fields:
func (_m *GreeterService) Greet() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GreetInDefaultMsg provides a mock function with given fields:
func (_m *GreeterService) GreetInDefaultMsg() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
